### ISSUE TITLE
你好，想请教下，关于flasky的使用

### ISSUE THREAD

**Issue by WuYiP** [zhengguanji/flasky#1]
我这几天一直在看About Miguel的Flask Web Development，在他的github上看到你的留言，知道你对这方面有一定的研究，能否留个邮箱，请教下你这方面的问题，谢谢！

**Comment by zhengguanji** [comment]
@WuYiP 不知道你想请教啥，说研究我能有什么研究啊，就是看他的书，看完之后不懂就回头翻，书里没有的就Google

**Comment by WuYiP** [comment]
我现在的状况是用户已经登录，但是用户的账号还未确认，在网页上显示给我的就是you have not confirmed your account yet.我不知道怎么办？我是试过python manage.py shell 中直接注册＞＞ｕ＝Ｕｓｅｒ（ｅｍａｉｌ＝＇ｊｏｈｎ＠ｅｘａｍｐｌｅ．ｃｏｍ＇，ｕｓｅｒｎａｍｅ＝＇ｊｏｈｎ＇，ｐａｓｓｗｏｒｄ＝＇ｃａｔ＇）
＞＞ｄｂ．ｓｅｓｓｉｏｎ．ａｄｄ（ｕ）
＞＞ｄｂ．ｓｅｓｓｉｏｎ．ｃｏｍｍｉｔ（）
然而这样不行，我不知你是怎么操作的，能给个意见吗？我这项目里面到目前为止除了安装所需要的模块外，其他都没有改过，我查了下书，就觉得应该是数据库和邮箱没有设置好，但是不知怎么操作？

**Comment by zhengguanji** [comment]
@WuYiP 不知道你看到第几章了，书里面是注册一个帐号后然后登录的时候他会发送验证邮件到你的邮箱，然后点击验证链接就可以确认了，我想你最起码看到第六章了吧，第六章书里的是注册账号之后它会发送验证邮件到你的邮箱，为了收到验证邮件你注册的邮箱必须用真的邮箱，而不是书里面的example.com邮箱，这书坑就坑在这里，一些细节没讲清楚，我之前看也是咬着牙忍着看完的，注册之前为了能发送邮件你还要在命令行设置环境变量，就是下面这两个：
```
(venv) $ set MAIL_USERNAME=<Gmail username>
(venv) $ set MAIL_PASSWORD=<Gmail password>
# 在mac或者Linux下，记得把set换成export
```
另外，不知道你看的是中文版还是英文版，如果是英文版看得费劲，还是看回中文版吧，别听别人说编程书最好看英文版的你就要求自己看英文版，这书中文版翻译得并不烂，你有问题还是尽量Google，专业问题别用baidu，很多东西搜不到，用Google的时候中文搜不到就换英文关键词来搜，搜不到再问吧，问人是最没效率的，你问编程的问题可以去Stackoverflow问，中文的有个类似的网站：Segmentfault，Stackoverflow上面大神多一些，不过是英文的你英文好就用Stackoverflow吧，我又好一些问题都是Google找到Stackoverflow上面的回答来解决的

**Comment by WuYiP** [comment]
我之前就有尝试你说的添加两个环境变量但是未成功，给我报错export MAIL_USERNAME=<Gmail username>
bash: syntax error near unexpected token `newline'
我后来在运行下我的python mange.py runserver时候发现我追踪到的错误是这个
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xiaowu/share/flask/venv/1/flasky/app/email.py", line 9, in send_async_email
    mail.send(msg)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
    message.send(connection)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 168, in send
    message.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 736, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/?p=WantAuthError z74sm18071408pfd.70 - gsmtp', 'Flasky Admin <flasky@example.com>')
我不知道你是否遇到过这问题

**Comment by Zhang21** [comment]
可以选择跳过邮箱验证，就是不要这部分

**Comment by zhengguanji** [comment]
@WuYiP 你的MAIL_USERNAME等号后面是空的没值的吗，看报错你用的貌似是Google的邮箱，Google的邮箱不FQ国内用不了，换国内的邮箱吧，我前面说了，别用xxx@example.com这样的邮箱，这根本不是真的邮箱，作者是为了举例才写了这种邮箱，实际的代码要用真正的邮箱，去找我的代码看一下吧

**Comment by WuYiP** [comment]
我看了你的configure.py尝试改下了里面的邮箱如下：
class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'hard to guess string'
    SSL_DISABLE = False
    SQLALCHEMY_COMMIT_ON_TEARDOWN = True
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_RECORD_QUERIES = True

    MAIL_SERVER =# 'smtp.qq.com'
    MAIL_PORT = 25
    MAIL_USE_TLS = True
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    FLASKY_MAIL_SUBJECT_PREFIX = '[Flasky]'
    FLASKY_MAIL_SENDER =#  os.environ.get('MAIL_USERNAME')
    FLASKY_ADMIN = os.environ.get('FLASKY_ADMIN')
    FLASKY_POSTS_PER_PAGE = 20
    FLASKY_FOLLOWERS_PER_PAGE = 50
    FLASKY_COMMENTS_PER_PAGE = 30
    FLASKY_SLOW_DB_QUERY_TIME=0.5
再次运行python manage.py runserver，最后出现如下的错误
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xiaowu/share/flask/venv/1/flasky/app/email.py", line 9, in send_async_email
    mail.send(msg)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
    message.send(connection)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 156, in send
    "The message does not specify a sender and a default sender "
AssertionError: The message does not specify a sender and a default sender has not been configured
发现这次是默认邮箱没有配置好，这个应该在哪里设置

**Comment by WuYiP** [comment]
@zhengguanji 我看了你的configure.py尝试改下了里面的邮箱如下：
class Config:
SECRET_KEY = os.environ.get('SECRET_KEY') or 'hard to guess string'
SSL_DISABLE = False
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_RECORD_QUERIES = True

MAIL_SERVER =# 'smtp.qq.com'
MAIL_PORT = 25
MAIL_USE_TLS = True
MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
FLASKY_MAIL_SUBJECT_PREFIX = '[Flasky]'
FLASKY_MAIL_SENDER =#  os.environ.get('MAIL_USERNAME')
FLASKY_ADMIN = os.environ.get('FLASKY_ADMIN')
FLASKY_POSTS_PER_PAGE = 20
FLASKY_FOLLOWERS_PER_PAGE = 50
FLASKY_COMMENTS_PER_PAGE = 30
FLASKY_SLOW_DB_QUERY_TIME=0.5

再次运行python manage.py runserver，最后出现如下的错误
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/xiaowu/share/flask/venv/1/flasky/app/email.py", line 9, in send_async_email
mail.send(msg)
File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
message.send(connection)
File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 351, in send
connection.send(self)
File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 156, in send
"The message does not specify a sender and a default sender "
AssertionError: The message does not specify a sender and a default sender has not been configured
发现这次是默认邮箱没有配置好，这个应该在哪里设置

**Comment by WuYiP** [comment]
@zhengguanji 图中#两个位置是修改的部分

**Comment by WuYiP** [comment]
@zhengguanji 我看了你的config.py代码，按照你代码改了下
class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'hard to guess string'
    SSL_DISABLE = False
    SQLALCHEMY_COMMIT_ON_TEARDOWN = True
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_RECORD_QUERIES = True

    MAIL_SERVER = 'smtp.qq.com'
    MAIL_PORT = 25
    MAIL_USE_TLS = True
    MAIL_USE_SSL = False
    MAIL_USERNAME =  os.environ.get( '346639361@qq.com')
    MAIL_PASSWORD =  os.environ.get('bzwepxoooqsdcafj')
    FLASKY_MAIL_SUBJECT_PREFIX = '[Flasky]'
    FLASKY_MAIL_SENDER = os.environ.get('346639361@qq.com')
    FLASKY_ADMIN = os.environ.get('FLASKY_ADMIN')
    FLASKY_POSTS_PER_PAGE = 20
    FLASKY_FOLLOWERS_PER_PAGE = 50
    FLASKY_COMMENTS_PER_PAGE = 30
    FLASKY_SLOW_DB_QUERY_TIME=0.5
发现还是同样的错误
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xiaowu/share/flask/venv/1/flasky/app/email.py", line 9, in send_async_email
    mail.send(msg)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 416, in send
    message.send(connection)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/home/xiaowu/share/flask/venv/local/lib/python2.7/site-packages/flask_mail.py", line 156, in send
    "The message does not specify a sender and a default sender "
AssertionError: The message does not specify a sender and a default sender has not been configured

**Comment by zhengguanji** [comment]
@WuYiP 我的邮箱收到你的回答，但是上来Github发现你自己删掉了评论，我发现你根本没看懂那几个变量是用来干嘛，更不知道怎么设置，这些书里有讲，我只能告诉你，回头翻书吧，另外我发现你貌似连错误提示都看不懂，还有你连上网搜一下都不会，自己谷歌搜“flask 发送邮件”就能找到一大堆，连搜都不愿意搜一下我也是没话好说了，这是我搜到的一些，
https://www.zhihu.com/question/38047858
http://www.jianshu.com/p/3d717415121b
http://www.pythondoc.com/flask-mega-tutorial/email.html
http://fedcuit.github.io/blog/2015/04/06/problem-with-python-mail/
http://cocode.cc/t/flask-mail-error553/3841
http://opsnotes.net/2015/07/14/flask-mail/
如果你真的不愿意回头翻书也不肯自己上网搜一下，那我就实在帮不了你了

**Comment by WuYiP** [comment]
@zhengguanji 我已经解决这问题了，所以才把之前的问题给删掉，非常感谢你的帮助
